/*
* Copyright Regione Piemonte - 2021
* SPDX-License-Identifier: EUPL-1.2-or-later.
*/
ALTER SEQUENCE IF EXISTS seq_id_legge RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_provvedimento RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_tipo_dr RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_dr RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_legge_provv_dr RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_parere RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_percentuale RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_rendiconto RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_stato_finanziamento RESTART WITH 11;
ALTER SEQUENCE IF EXISTS seq_id_tetto_max RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_tipo_erogazione RESTART WITH 3;
ALTER SEQUENCE IF EXISTS seq_id_tipo_forma_associativa RESTART WITH 7;
ALTER SEQUENCE IF EXISTS seq_id_forma_associativa RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_vincolo_popolazione RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_richiesta RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_richiedente RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_finanziamento RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_finanziamento_rinuncia RESTART WITH 1;
ALTER SEQUENCE IF EXISTS seq_id_erogazione RESTART WITH 1;
